name: Build and Deploy API

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Needed for AWS CLI
permissions:
      id-token: write
      contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      
      - name: Build API with Maven
        working-directory: ./api
        run: mvn clean package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Set up deployment environment
        uses: actions/checkout@v4
        
      - uses: actions/setup-python@v4
      - uses: aws-actions/setup-sam@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws-region: us-east-1
          
      - name: Build and Deploy SAM
        working-directory: ./api
        run: |
          sam build --use-container
          sam deploy --no-confirm-changeset \
                     --no-fail-on-empty-changeset \
                     --stack-name lotlytics-api \
                     --resolve-s3 \
                     --capabilities CAPABILITY_IAM \
                     --parameter-overrides \
                     DatabaseUrl="${{ secrets.LOTLYTICS_DB_ENDPOINT }}" \
                     DatabaseUsername="${{ secrets.LOTLYTICS_DB_USERNAME }}" \
                     DatabasePassword="${{ secrets.LOTLYTICS_DB_PASSWORD }}" \
                     DynamoDBTable="${{ secrets.LOTLYTICS_DB_EVENTS_TABLE_NAME }}" \
                     CorsAllowedOrigin="${{ secrets.LOTLYTICS_SITE_ORIGIN }}"
