name: Deploy and Initialize Database

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Needed for AWS CLI
permissions:
      id-token: write
      contents: read
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set up deployment environment
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws-region: us-east-1
      - name: Build Cloudformation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1.2.0
        with:
          name: lotlytics-db
          template: ./database/dynamodb/template.yml
          parameter-overrides: 
            DBUser="${{ secrets.LOTLYTICS_DB_USERNAME }}",
            DBPassword="${{ secrets.LOTLYTICS_DB_PASSWORD }}",
            VPCCidrBlock="${{ secrets.LOTLYTICS_DB_VPC_CIDR_BLOCK }}",
            Subnet1CidrBlock="${{ secrets.LOTLYTICS_DB_SUBNET_1_CIDR_BLOCK }}",
            Subnet2CidrBlock="${{ secrets.LOTLYTICS_DB_SUBNET_2_CIDR_BLOCK }}"

  initialize:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set up initialization environment
        run: apt install postgresql-client-16
